global:
  scrape_interval:     15s
  evaluation_interval: 30s

scrape_configs:
- job_name: zpool-exporter
  scrape_interval: 20s
  scrape_timeout:  10s
  static_configs:
  - targets: ['localhost:8000']
    labels:
      source: zpool-exporter
